# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prompt_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(418, 200)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/notification.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("border:none;\n"
"outline:none;\n"
"background: #F0F0F0;\n"
"border-radius:10px")
        self.time_label = QtWidgets.QLabel(Dialog)
        self.time_label.setGeometry(QtCore.QRect(0, 20, 411, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_label.sizePolicy().hasHeightForWidth())
        self.time_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(20)
        self.time_label.setFont(font)
        self.time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label.setObjectName("time_label")
        self.btn_ok = QtWidgets.QPushButton(Dialog)
        self.btn_ok.setGeometry(QtCore.QRect(170, 150, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.btn_ok.setFont(font)
        self.btn_ok.setStyleSheet("background: #000;\n"
"color: #fff;\n"
"border: none;\n"
"border-radius: 10px")
        self.btn_ok.setObjectName("btn_ok")
        self.message_label = QtWidgets.QLabel(Dialog)
        self.message_label.setGeometry(QtCore.QRect(66, 62, 291, 61))
        self.message_label.setStyleSheet("background: white")
        self.message_label.setAlignment(QtCore.Qt.AlignCenter)
        self.message_label.setObjectName("message_label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Notification"))
        self.time_label.setText(_translate("Dialog", "11:02"))
        self.btn_ok.setText(_translate("Dialog", "OK"))
        self.message_label.setText(_translate("Dialog", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
