# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(390, 640)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/add-user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background : #363636;")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 60, 390, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(243,243,243)")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.invalid = QtWidgets.QLabel(Dialog)
        self.invalid.setGeometry(QtCore.QRect(0, 470, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.invalid.setFont(font)
        self.invalid.setStyleSheet("color: #FFFF33;")
        self.invalid.setAlignment(QtCore.Qt.AlignCenter)
        self.invalid.setObjectName("invalid")
        self.password = QtWidgets.QLineEdit(Dialog)
        self.password.setGeometry(QtCore.QRect(160, 240, 200, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password.sizePolicy().hasHeightForWidth())
        self.password.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.password.setFont(font)
        self.password.setStyleSheet("\n"
"color: rgb(243,243,243);\n"
"border-radius: 10px;\n"
"border: 1px solid rgb(243,243,243)")
        self.password.setText("")
        self.password.setObjectName("password")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(38, 179, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(243,243,243)")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(38, 250, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(243,243,243)")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(38, 322, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(243,243,243)")
        self.label_4.setObjectName("label_4")
        self.signupbutton = QtWidgets.QPushButton(Dialog)
        self.signupbutton.setGeometry(QtCore.QRect(130, 410, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.signupbutton.setFont(font)
        self.signupbutton.setStyleSheet("background: rgb(243, 243, 243);\n"
"color: rgb(54, 54, 54);\n"
"border-radius: 10px;\n"
"border: none;")
        self.signupbutton.setObjectName("signupbutton")
        self.btnback = QtWidgets.QPushButton(Dialog)
        self.btnback.setGeometry(QtCore.QRect(57, 74, 61, 41))
        self.btnback.setStyleSheet("border: none\n"
"")
        self.btnback.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnback.setIcon(icon1)
        self.btnback.setIconSize(QtCore.QSize(64, 64))
        self.btnback.setObjectName("btnback")
        self.email = QtWidgets.QLineEdit(Dialog)
        self.email.setGeometry(QtCore.QRect(160, 170, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.email.setFont(font)
        self.email.setStyleSheet("color: rgb(243,243,243);\n"
"border-radius: 10px;\n"
"border: 1px solid rgb(243,243,243);")
        self.email.setObjectName("email")
        self.confirmpass = QtWidgets.QLineEdit(Dialog)
        self.confirmpass.setGeometry(QtCore.QRect(160, 312, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.confirmpass.setFont(font)
        self.confirmpass.setStyleSheet("color: rgb(243,243,243);\n"
"border-radius: 10px;\n"
"border: 1px solid rgb(243,243,243)")
        self.confirmpass.setObjectName("confirmpass")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Sign Up"))
        self.label.setText(_translate("Dialog", "Sign up"))
        self.invalid.setText(_translate("Dialog", "Invalid email"))
        self.label_2.setText(_translate("Dialog", "Email"))
        self.label_3.setText(_translate("Dialog", "Password"))
        self.label_4.setText(_translate("Dialog", "Confirm Pass"))
        self.signupbutton.setText(_translate("Dialog", "Sign up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
