# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signin_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(390, 640)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/log-in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background : #363636;\n"
"")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(37, 179, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(243,243,243)")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(37, 250, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(243,243,243)")
        self.label_19.setObjectName("label_19")
        self.invalid = QtWidgets.QLabel(Dialog)
        self.invalid.setGeometry(QtCore.QRect(-1, 313, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.invalid.setFont(font)
        self.invalid.setStyleSheet("color: #FFFF33;")
        self.invalid.setAlignment(QtCore.Qt.AlignCenter)
        self.invalid.setObjectName("invalid")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(-1, 60, 390, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(28)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(243,243,243)")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.email = QtWidgets.QLineEdit(Dialog)
        self.email.setGeometry(QtCore.QRect(159, 170, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.email.setFont(font)
        self.email.setStyleSheet("color: rgb(243,243,243);\n"
"border-radius: 10px;\n"
"border: 1px solid rgb(243,243,243);")
        self.email.setObjectName("email")
        self.password = QtWidgets.QLineEdit(Dialog)
        self.password.setGeometry(QtCore.QRect(159, 240, 200, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password.sizePolicy().hasHeightForWidth())
        self.password.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.password.setFont(font)
        self.password.setStyleSheet("\n"
"color: rgb(243,243,243);\n"
"border-radius: 10px;\n"
"border: 1px solid rgb(243,243,243)")
        self.password.setText("")
        self.password.setObjectName("password")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(79, 459, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_21.setObjectName("label_21")
        self.loginbutton = QtWidgets.QPushButton(Dialog)
        self.loginbutton.setGeometry(QtCore.QRect(129, 373, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.loginbutton.setFont(font)
        self.loginbutton.setStyleSheet("background: rgb(243, 243, 243);\n"
"color: rgb(54, 54, 54);\n"
"border-radius: 10px;\n"
"border: none;")
        self.loginbutton.setObjectName("loginbutton")
        self.createaccbutton = QtWidgets.QPushButton(Dialog)
        self.createaccbutton.setGeometry(QtCore.QRect(219, 453, 93, 28))
        self.createaccbutton.setStyleSheet("border:none;\n"
"color:#363636;;\n"
"background: #FFFF33;\n"
"border-radius: 10px")
        self.createaccbutton.setObjectName("createaccbutton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Sign In"))
        self.label_18.setText(_translate("Dialog", "Email"))
        self.label_19.setText(_translate("Dialog", "Password"))
        self.invalid.setText(_translate("Dialog", "Invalid email or password"))
        self.label_20.setText(_translate("Dialog", "Sign in"))
        self.label_21.setText(_translate("Dialog", "Don\'t have account?"))
        self.loginbutton.setText(_translate("Dialog", "Sign in"))
        self.createaccbutton.setText(_translate("Dialog", "Sign Up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
