# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_chat.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(283, 51)
        self.chat_bot_widget = QtWidgets.QWidget(Form)
        self.chat_bot_widget.setGeometry(QtCore.QRect(0, 0, 281, 51))
        self.chat_bot_widget.setObjectName("chat_bot_widget")
        self.chat_bot = QtWidgets.QLabel(self.chat_bot_widget)
        self.chat_bot.setGeometry(QtCore.QRect(50, 5, 231, 41))
        self.chat_bot.setStyleSheet("background: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding-left: 10px")
        self.chat_bot.setObjectName("chat_bot")
        self.label_7 = QtWidgets.QLabel(self.chat_bot_widget)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("icon/bot.png"))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.chat_bot.setText(_translate("Form", "It\'s 9:00 pm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
